/*!
 * by zhangxinxu(.com) 2012-12-27
 * you can visit http://www.zhangxinxu.com/wordpress/?p=3855 to get more infomation
 * under MIT license
*/
var Parabola=function(d,t,g){
  /*! requestAnimationFrame.js
     * by zhangxinxu 2013-09-30
    */
  (function(){var b=0;var c=["webkit","moz"];for(var a=0;a<c.length&&!window.requestAnimationFrame;++a){window.requestAnimationFrame=window[c[a]+"RequestAnimationFrame"];window.cancelAnimationFrame=window[c[a]+"CancelAnimationFrame"]||window[c[a]+"CancelRequestAnimationFrame"]}if(!window.requestAnimationFrame){window.requestAnimationFrame=function(z,w){var v=new Date().getTime();var x=Math.max(0,16.7-(v-b));var y=window.setTimeout(function(){z(v+x)},x);b=v+x;return y}}if(!window.cancelAnimationFrame){window.cancelAnimationFrame=function(v){clearTimeout(v)}}}());var i={speed:166.67,curvature:0.001,endScale:"1",progress:function(){},complete:function(){}};var p={};g=g||{};for(var u in i){p[u]=g[u]||i[u]}var e="margin",r=document.createElement("div");if("oninput" in r){["","ms","webkit"].forEach(function(b){var a=b+(b?"T":"t")+"ransform";if(a in r.style){e=a}})}var s=p.curvature,q=0,o=0;var k=true;if(d&&t&&d.nodeType==1&&t.nodeType==1){var n={},j={};var h={},m={};var f={},l={};this.position=function(){if(k==false){return this}var b=document.documentElement.scrollLeft||document.body.scrollLeft,a=document.documentElement.scrollTop||document.body.scrollTop;if(e=="margin"){d.style.marginLeft=d.style.marginTop="0px"}else{d.style[e]="translate(0, 0)"}n=d.getBoundingClientRect();j=t.getBoundingClientRect();h={x:n.left+(n.right-n.left)/2+b,y:n.top+(n.bottom-n.top)/2+a};m={x:j.left+(j.right-j.left)/2+b,y:j.top+(j.bottom-j.top)/2+a};f={x:0,y:0};l={x:-1*(h.x-m.x),y:-1*(h.y-m.y)};q=(l.y-s*l.x*l.x)/l.x;return this};this.move=function(){if(k==false){return this}var a=0,b=l.x>0?1:-1;var v=1;var c=function(){var A=2*s*a+q;var C=Math.sqrt(p.speed/(A*A+1));a=a+b*C;var z=(1-(p.endScale*1))*C/Math.abs(f.x-l.x);v=v-z;if((b==1&&a>l.x)||(b==-1&&a<l.x)){a=l.x}var w=a,B=s*w*w+q*w;d.setAttribute("data-center",[Math.round(w),Math.round(B)].join());if(e=="margin"){d.style.marginLeft=w+"px";d.style.marginTop=B+"px"}else{d.style[e]="translate("+[w+"px",B+"px"].join()+")"+"scale("+v+")"}if(a!==l.x){p.progress(w,B);window.requestAnimationFrame(c)}else{p.complete();k=true}};window.requestAnimationFrame(c);k=false;return this};this.init=function(){this.position().move();return this}}};

moudle.exports = Parabola;
